package com.example.damiProd.controller;

import com.example.damiProd.domain.RecurringIgienizare;
import com.example.damiProd.domain.RecurringOccurrence;
import com.example.damiProd.service.RecurringIgienizareService;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Map;

@RestController
@RequestMapping("/api/recurring-igienizari")
public class RecurringIgienizareController {

    private final RecurringIgienizareService service;

    public RecurringIgienizareController(RecurringIgienizareService service) {
        this.service = service;
    }

    @GetMapping
    public List<RecurringIgienizare> getAll() {
        return service.getAll();
    }

    @GetMapping("/active")
    public List<RecurringIgienizare> getActive() {
        return service.getActiveOnly();
    }

    @GetMapping("/{id}")
    public RecurringIgienizare getById(@PathVariable Long id) {
        return service.getById(id);
    }

    @GetMapping("/client/{clientId}")
    public List<RecurringIgienizare> getByClient(@PathVariable Long clientId) {
        return service.getByClient(clientId);
    }

    @PostMapping("/client/{clientId}")
    public RecurringIgienizare create(@PathVariable Long clientId,
                                      @RequestBody RecurringIgienizare plan) {
        return service.create(clientId, plan);
    }

    @PutMapping("/{id}/assign-route")
    public RecurringIgienizare assignRoute(@PathVariable Long id,
                                           @RequestBody Map<String, Long> body) {
        Long routeId = body.get("routeId");
        if (routeId == null) throw new RuntimeException("routeId is required");
        return service.assignRoute(id, routeId);
    }

    @PutMapping("/{id}/deactivate")
    public RecurringIgienizare deactivate(@PathVariable Long id) {
        return service.deactivate(id);
    }

    @GetMapping("/{id}/occurrences")
    public List<RecurringOccurrence> getOccurrences(@PathVariable Long id) {
        return service.getOccurrences(id);
    }

    /**
     * Check if a specific order was generated by a recurring plan.
     */
    @GetMapping("/is-recurring-order/{orderId}")
    public ResponseEntity<Map<String, Object>> isRecurringOrder(@PathVariable Long orderId) {
        List<RecurringIgienizare> allPlans = service.getAll();
        for (RecurringIgienizare plan : allPlans) {
            List<RecurringOccurrence> occs = service.getOccurrences(plan.getId());
            for (RecurringOccurrence occ : occs) {
                if (occ.getOrder() != null && occ.getOrder().getId().equals(orderId)) {
                    return ResponseEntity.ok(Map.of("isRecurring", true, "planId", plan.getId()));
                }
            }
        }
        return ResponseEntity.ok(Map.of("isRecurring", false));
    }
}
